In [3]:
import torch

In [5]:
x = torch.arange(12, dtype=torch.float32)
print(x)

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])


In [9]:
x.numel()

12

In [11]:
X = x.reshape(3,4)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [12]:
torch.zeros(4,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [13]:
torch.ones(3,4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [14]:
torch.rand(5,5)

tensor([[0.7212, 0.3332, 0.5118, 0.0622, 0.6613],
        [0.8143, 0.8307, 0.8609, 0.7520, 0.4605],
        [0.1549, 0.8355, 0.3322, 0.4887, 0.0467],
        [0.9884, 0.7239, 0.9307, 0.0904, 0.0799],
        [0.0742, 0.7791, 0.4693, 0.3305, 0.4177]])

In [17]:
torch.tensor([[1,2,3],[1,4,5],[2,5,2]])

tensor([[1, 2, 3],
        [1, 4, 5],
        [2, 5, 2]])

In [21]:
X


tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [26]:
X[1,0] = 2
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 2.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [30]:
X[1:3]

tensor([[ 2.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])